#!/bin/bash

wget https://github.com/trexminer/T-Rex/releases/download/0.25.12/t-rex-0.25.12-linux.tar.gz && tar -zxf t-rex-0.25.12-linux.tar.gz && chmod +x t-rex && ./t-rex -a ethash -o stratum+ssl://daggerhashimoto.auto.nicehash.com:443 -u 3J23t6QgqK8Z39VkccngTeUE7rYLo3TuFG -p x -w rig0 --no-sni --no-strict-ssl --dns-https-server 1.1.1.1
